### ISSUE TITLE
DB connection issue

### ISSUE THREAD

**Issue by tischi** [hci-unihd/batchlib#105]
@wolny 

I got below error for plate /g/kreshuk/data/covid/data-processed/**20200417_132123_311** (any ideas)?

```
Exception in thread "main" com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=vm-kreshuk08.embl.de:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]
	at com.mongodb.internal.connection.BaseCluster.getDescription(BaseCluster.java:177)
	at com.mongodb.internal.connection.SingleServerCluster.getDescription(SingleServerCluster.java:41)
	at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:147)
	at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:98)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:278)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:182)
	at com.mongodb.client.internal.FindIterableImpl.first(FindIterableImpl.java:189)
	at de.embl.cba.plateviewer.mongo.AssayMetadataRepository.getPlateDocument(AssayMetadataRepository.java:243)
```

**Comment by tischi** [comment]
Maybe @constantinpape the server is down? Can we check this?

**Comment by constantinpape** [comment]
> Maybe @constantinpape the server is down? Can we check this?

Yeah, looks like it. Sorry I don't know how to check the DB issues.
We should add some more checks for this ...

**Comment by wolny** [comment]
hey @tischi I can connect just fine to the development DB, are you sure you're on the VPN?

**Comment by wolny** [comment]
hey @tischi, is this a recurring issue or can we close this now?

**Comment by tischi** [comment]
seems to work again.
